AWSTemplateFormatVersion: '2010-09-09'
Description: AWS CloudFormation Template to create S3 bucket
Parameters:
  BucketName:
    Type: String
    Description: S3 bucket name
  EnableVersioning:
    Type: String
    AllowedValues: [Enabled, Disabled]
    Default: Disabled
    Description: Enable or disable versioning for S3 bucket
Resources:
  S3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Ref BucketName
      VersioningConfiguration:
        Status: !If
          - IsVersioningEnabled
          - Enabled
          - Suspended
Conditions:
  IsVersioningEnabled: !Equals [!Ref EnableVersioning, Enabled]
